
language: minimal

os: osx
osx_image: xcode9.1

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  - brew update
  - brew tap caskroom/cask
  - brew cask install powershell

install:
  - pwsh -c "& { $ProgressPreference = 'SilentlyContinue'; Install-Module -Force -Scope CurrentUser Pester, PSScriptAnalyzer, PSCodeCovIo; }"

script:
  - pwsh -c 'Invoke-ScriptAnalyzer -Path .'
  - pwsh -c '& {
      $res = Invoke-Pester -PassThru -CodeCoverage PSDefaults.psm1;
      Export-CodeCovIoJson -CodeCoverage $res.CodeCoverage -RepoRoot $pwd -Path coverage.json;
      if ($res.FailedCount -gt 0) {
        throw "$($res.FailedCount) tests failed."
      }
    }'

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.json